In [3]:
#This block splits a stacked 5d tensor StackedQueryKeyValue to q,k,v tensors and transpose them. 
#Both untransposed and transposed q,k,v tensors are dumped

import numpy as np
import sys
#create horizontally stacked Tensor
batchSize = 2
headSize = 40
sequenceLength = 4096
headCount = 8
#When you receive StackedQueryKeyValue, it will have a shape of {batchSize, sequenceLength, numHeads, 3, headSize}
stackedTensorSize = batchSize*sequenceLength*headCount*3*headSize
stackedTensor = np.arange(stackedTensorSize).reshape(batchSize, sequenceLength, headCount, 3, headSize)
print("stackedTensor.shape is",stackedTensor.shape)
stackedTensor.tofile('stackedTensor.txt',sep=" ",format="%s")
print("StackedTensor write complete")

#You can then split that tensor on the 4th dimension into 3 tensors with the same shape 
#{batchSize, sequenceLength, numHeads, 1, headSize} 
#(Query is the first tensor, Key is the second tensor and Value is the third tensor)

#split this stackedtensor along 4th dim
slicesList =  np.array_split(stackedTensor,3,3)
print("len(slicesList)", len(slicesList)) #returns 3
#sliceList contains the q,k,v tensors
#print(slicesList[0].shape)
#slicesList[0] = slicesList[0].reshape(batchSize, sequenceLength, headCount, headSize)
#print(slicesList[0].shape)

slicesList[0] = slicesList[0].reshape(batchSize, sequenceLength, headCount, headSize)
slicesList[1] = slicesList[1].reshape(batchSize, sequenceLength, headCount, headSize)
slicesList[2] = slicesList[2].reshape(batchSize, sequenceLength, headCount, headSize)
print("slicesList[0].shape=",slicesList[0].shape)
print("slicesList[1].shape=",slicesList[1].shape)
print("slicesList[2].shape=",slicesList[2].shape)

print("slicesList[0].strides=",slicesList[0].strides)
print("slicesList[1].strides=",slicesList[1].strides)
print("slicesList[2].strides=",slicesList[2].strides)

slicesList[0].tofile('qkv_QTensor',sep=" ",format="%s")
slicesList[1].tofile('qkv_KTensor',sep=" ",format="%s")
slicesList[2].tofile('qkv_VTensor',sep=" ",format="%s")

print("qkv tensor write complete")

#Those tensors can then be easily reshaped to 4D tensors of shape {batchSize, sequenceLength, headCount, headSize}
#4.	Then, you need to transpose the query tensor to the {batchSize, headCount, sequenceLength, headSize} shape
#5.	You also need to transpose the key tensor to the {batchSize, headCount, headSize, kvSequenceLength} shape
#6.	You also need to transpose the value tensor to the {batchSize, headCount, kvSequenceLength, vHeadSize} shape

#Transpose

#Those tensors can then be easily reshaped to 4D tensors of shape {batchSize, sequenceLength, headCount, headSize} 0,1,2,3
#Then, you need to transpose the query tensor to the {batchSize, headCount, sequenceLength, headSize} shape 0,2,1,3
#You also need to transpose the key tensor to the {batchSize, headCount, headSize, kvSequenceLength} shape 0,2,3,1
#You also need to transpose the value tensor to the {batchSize, headCount, kvSequenceLength, vHeadSize} shape 0,2,1,3

slicesList[0] = slicesList[0].transpose(0,2,1,3)
slicesList[1] = slicesList[1].transpose(0,2,3,1)
slicesList[2] = slicesList[2].transpose(0,2,1,3)

slicesList[0].tofile('qkv_QTensorTranspose',sep=" ",format="%s")
slicesList[1].tofile('qkv_KTensorTranspose',sep=" ",format="%s")
slicesList[2].tofile('qkv_VTensorTranspose',sep=" ",format="%s")

print("slicesList[0].shape=",slicesList[0].shape)
print("slicesList[1].shape=",slicesList[1].shape)
print("slicesList[2].shape=",slicesList[2].shape)

print("slicesList[0].strides=",slicesList[0].strides)
print("slicesList[1].strides=",slicesList[1].strides)
print("slicesList[2].strides=",slicesList[2].strides)

print("qkv transposed tensor write complete")

stackedTensor.shape is (2, 4096, 8, 3, 40)
StackedTensor write complete
len(slicesList) 3
slicesList[0].shape= (2, 4096, 8, 40)
slicesList[1].shape= (2, 4096, 8, 40)
slicesList[2].shape= (2, 4096, 8, 40)
slicesList[0].strides= (15728640, 3840, 480, 4)
slicesList[1].strides= (15728640, 3840, 480, 4)
slicesList[2].strides= (15728640, 3840, 480, 4)
qkv tensor write complete
slicesList[0].shape= (2, 8, 4096, 40)
slicesList[1].shape= (2, 8, 40, 4096)
slicesList[2].shape= (2, 8, 4096, 40)
slicesList[0].strides= (15728640, 480, 3840, 4)
slicesList[1].strides= (15728640, 480, 4, 3840)
slicesList[2].strides= (15728640, 480, 3840, 4)
qkv transposed tensor write complete


In [1]:
#This block splits a stacked 5d tensor StackedKeyValue to k,v tensors and transpose them. 
#Both untransposed and transposed k,v tensors are dumped

import numpy as np
import sys
batchSize = 2
kvSequenceLength = 64
headCount = 8
headSize = 160

#When you receive StackedKeyValue, it will have a shape of {batchSize, kvSequenceLength, numHeads, 2, headSize}
stackedTensorSize = batchSize*kvSequenceLength*headCount*2*headSize
stackedTensor = np.arange(stackedTensorSize).reshape(batchSize, kvSequenceLength, headCount, 2, headSize)
print("stackedTensor.shape is",stackedTensor.shape)
stackedTensor.tofile('stackedTensor.txt',sep=" ",format="%s")
print("StackedTensor write complete")

#You can then split that tensor on the 4th dimension into 2 tensors with the same shape 
#{batchSize, kvSequenceLength, numHeads, 1, headSize} 
#(Key is the first tensor, Value is the second tensor )

#split this stackedtensor along 4th dim
slicesList =  np.array_split(stackedTensor,2,3)
print("len(slicesList)", len(slicesList)) #returns 2


slicesList[0] = slicesList[0].reshape(batchSize, kvSequenceLength, headCount, headSize)
slicesList[1] = slicesList[1].reshape(batchSize, kvSequenceLength, headCount, headSize)

print("slicesList[0].shape=",slicesList[0].shape)
print("slicesList[1].shape=",slicesList[1].shape)
print("slicesList[0].strides=",slicesList[0].strides)
print("slicesList[1].strides=",slicesList[1].strides)

slicesList[0].tofile('kv_KTensor',sep=" ",format="%s")
slicesList[1].tofile('kv_VTensor',sep=" ",format="%s")

print("kv tensor write complete")

#Those tensors can then be easily reshaped to 4D tensors of shape {batchSize, kvSequenceLength, headCount, headSize) 0,1,2,3
#Then, you need to transpose the key tensor to the {batchSize, headCount, headSize, kvSequenceLength} shape 0,2,3,1
#You also need to transpose the value tensor to the {batchSize, headCount, kvSequenceLength, vHeadSize} shape 0,2,1,3

slicesList[0] = slicesList[0].transpose(0,2,3,1) #key indices are moved twice: double transpose
slicesList[1] = slicesList[1].transpose(0,2,1,3) #value

slicesList[0].tofile('kv_KTensorTranspose',sep=" ",format="%s")
slicesList[1].tofile('kv_VTensorTranspose',sep=" ",format="%s")

print("kv transposed tensor write complete")

stackedTensor.shape is (2, 64, 8, 2, 160)
StackedTensor write complete
len(slicesList) 2
slicesList[0].shape= (2, 64, 8, 160)
slicesList[1].shape= (2, 64, 8, 160)
slicesList[0].strides= (655360, 10240, 1280, 4)
slicesList[1].strides= (655360, 10240, 1280, 4)
kv tensor write complete
kv transposed tensor write complete


In [2]:
#5d QTensor transpose
#6.	As for the Query tensor, it will have a shape of {batchSize, sequenceLength, hiddenSize}. 
#This can be reshaped to a 4D tensor of shape {batchSize, sequenceLength, headCount, headSize}  0,1,2,3,
# and then transposed to a tensor of shape {batchSize, headCount, sequenceLength, headSize} 0,2,1,3

import numpy as np
import sys
batchSize = 2
QsequenceLength = 256
hiddenSize = 1280
headCount = 8
headSize = 160

QTensorSize = batchSize*QsequenceLength*headCount*1*headSize
QTensor = np.arange(QTensorSize).reshape(batchSize, QsequenceLength, headCount, headSize) # working
#QTensor = np.arange(QTensorSize).reshape(batchSize, QsequenceLength, headCount*headSize)
#QTensor = np.arange(QTensorSize).reshape(1,1,batchSize, QsequenceLength, hiddenSize)
#QTensor = np.reshape(batchSize, QsequenceLength, headCount, headSize)
print("QTensor.shape is",QTensor.shape)
QTensor.tofile('QTensorBeforeTranspose',sep=" ",format="%s")
print("QTensorBeforeTranspose write complete")
QTensorTranspose = QTensor.transpose(0,2,1,3)
print("QTensorTranspose.shape is",QTensorTranspose.shape)
print("QTensorTranspose.strides is",QTensorTranspose.strides)
QTensorTranspose.tofile('QTensorAfterTranspose',sep=" ",format="%s")
print("QTensorAfterTranspose write complete")


QTensor.shape is (2, 256, 8, 160)
QTensorBeforeTranspose write complete
QTensorTranspose.shape is (2, 8, 256, 160)
QTensorTranspose.strides is (1310720, 640, 5120, 4)
QTensorAfterTranspose write complete


In [11]:
#Tensor softmax using dimensions of output of Gemm(q,k) thats of shape 
#{batchSize, headCount, sequenceLength, kvSequenceLength}

import numpy as np
import sys
#batchSize = 2
#headCount = 8
#sequenceLength = 256
#kvSequenceLength = 64
batchSize = 2
headCount = 8
sequenceLength = 256
kvSequenceLength = 64

def softmax(z):
    #assert len(z.shape) == 2
    s = np.max(z, axis=3)
    s = s[:, :, : ,np.newaxis] # necessary step to do broadcasting
    e_x = np.exp(z - s)
    div = np.sum(e_x, axis=3)
    div = div[:, :, :, np.newaxis] # dito
    return e_x / div

inTensorSize = batchSize*headCount*sequenceLength*kvSequenceLength
inTensor = np.full((batchSize, headCount, sequenceLength, kvSequenceLength), 3)
print(softmax(inTensor))

[[[[0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   ...
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]]

  [[0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   ...
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]]

  [[0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   [0.015625 0.015625 0.015625 ... 0.015625 0.015625 0.015625]
   ...
   [0.015625 0.015625 0.015625

In [1]:
#9.After softmax, it’s time to do the second GEMM, which is a dot product of the result of Softmax and the Value tensor. 
#The result of this GEMM will have shape {batchSize, headCount, sequenceLength, vHeadSize}
#10.Then, transpose the result of the second GEMM into a tensor that has shape {batchSize, sequenceLength, headCount, vHeadSize}

import numpy as np
import sys
batchSize = 2
headCount = 8
sequenceLength = 4096
vheadSize = 40

MhaGemm1OutTensorSize = batchSize*sequenceLength*headCount*vheadSize
MhaGemm1OutTensor = np.arange(MhaGemm1OutTensorSize).reshape(batchSize, headCount, sequenceLength, vheadSize) #0,1,2,3
print("MhaGemm1OutTensor.shape is",MhaGemm1OutTensor.shape)
MhaGemm1OutTensor.tofile('MhaGemm1OutTensor',sep=" ",format="%s")
print("MhaGemm1OutTensor write complete")
MhaGemm1OutTensorTranspose = MhaGemm1OutTensor.transpose(0,2,1,3) #swap headcount and seqlen indices
print("MhaGemm1OutTensorTranspose.shape is",MhaGemm1OutTensorTranspose.shape)
MhaGemm1OutTensorTranspose.tofile('MhaGemm1OutTensorTranspose',sep=" ",format="%s")
print("MhaGemm1OutTensorTranspose write complete")


MhaGemm1OutTensor.shape is (2, 8, 4096, 40)
MhaGemm1OutTensor write complete
MhaGemm1OutTensorTranspose.shape is (2, 4096, 8, 40)
MhaGemm1OutTensorTranspose write complete


In [9]:
#int q_sizes[dim_count] = {2,1,2,32}; //{batch, headcount, seqlen,headsize } = //{batch, headcount, M,K}
#int k_sizes[dim_count] = {2,1,32,2 }; //{batch, headcount,headsize, kvseqlen } = ////{batch, headcount,K,N}
#int out_sizes[dim_count] = { 2,1,2,2 }; // {batchSize, headCount, sequenceLength, kvSequenceLength}

import numpy as np
import sys
#Gemm using matmul
#{2,1,2,32}
#2,8,256,160
#int q_sizes[dim_count] = { 2,8,256,160 }; //{batch, headcount, seqlen,headsize } = //{batch, headcount, M,K}
#int k_sizes[dim_count] = { 2,8,160,64 }; //{batch, headcount, headsize,kvseqlen } = //{batch, headcount, K,N}
batchSize=2
headcount=8
seqlen=256
headsize=160
kvseqlen=64
#QTensor shape = {batch, headcount, seqlen,headsize}
qTensorSize = batchSize * headcount * seqlen * headsize
qTensor = np.arange(qTensorSize).reshape(batchSize, headcount, seqlen, headsize)
print("qTensor.shape=",qTensor.shape)
#KTensor shape = {batch, headcount, headsize, kvseqlen}
kTensorSize = batchSize * headcount * headsize * kvseqlen
kTensor = np.arange(kTensorSize).reshape(batchSize, headcount, headsize,kvseqlen)
print("kTensor.shape=",kTensor.shape)
print("qTensor=",qTensor)
print("kTensor=",kTensor)
res = np.matmul(qTensor,kTensor)
res.tofile('GemmOutTensor',sep=" ",format="%s")
print("gemm result=",res)
print(res.shape)


qTensor.shape= (2, 8, 256, 160)
kTensor.shape= (2, 8, 160, 64)
qTensor= [[[[     0      1      2 ...    157    158    159]
   [   160    161    162 ...    317    318    319]
   [   320    321    322 ...    477    478    479]
   ...
   [ 40480  40481  40482 ...  40637  40638  40639]
   [ 40640  40641  40642 ...  40797  40798  40799]
   [ 40800  40801  40802 ...  40957  40958  40959]]

  [[ 40960  40961  40962 ...  41117  41118  41119]
   [ 41120  41121  41122 ...  41277  41278  41279]
   [ 41280  41281  41282 ...  41437  41438  41439]
   ...
   [ 81440  81441  81442 ...  81597  81598  81599]
   [ 81600  81601  81602 ...  81757  81758  81759]
   [ 81760  81761  81762 ...  81917  81918  81919]]

  [[ 81920  81921  81922 ...  82077  82078  82079]
   [ 82080  82081  82082 ...  82237  82238  82239]
   [ 82240  82241  82242 ...  82397  82398  82399]
   ...
   [122400 122401 122402 ... 122557 122558 122559]
   [122560 122561 122562 ... 122717 122718 122719]
   [122720 122721 122722 ... 122877 

In [1]:
import numpy as np
import sys
a = np.array([1,2,3,4]).reshape(2,2)
print(a)
print(a.shape)
b = np.array([1,2,3,4]).reshape(2,2)
print(b.shape)
res = np.matmul(a,b)
print(res)
print(res.shape)

[[1 2]
 [3 4]]
(2, 2)
(2, 2)
[[ 7 10]
 [15 22]]
(2, 2)


In [ ]:
#int q_sizes[dim_count] = {2,1,2,32}; //{batch, headcount, seqlen,headsize } = //{batch, headcount, M,K}
#int k_sizes[dim_count] = {2,1,32,2 }; //{batch, headcount,headsize, kvseqlen } = ////{batch, headcount,K,N}
#int out_sizes[dim_count] = { 2,1,2,2 }; // {batchSize, headCount, sequenceLength, kvSequenceLength}


import numpy as np
import sys
a = np.array([1,2,3,4]).reshape(2,2)
print(a)
print(a.shape)
b = np.array([2,1]).reshape(2,1)
print(b.shape)
res = np.matmul(a,b)
print(res)
print(res.shape)

In [12]:
#gemm1 out transpose
#9.	After softmax, it’s time to do the second GEMM, which is a dot product of the result of Softmax and the Value tensor. 
#The result of this GEMM will have shape {batchSize, headCount, sequenceLength, vHeadSize}
#2,8,256,160
#10.Then, transpose the result of the second GEMM into a tensor that has shape 
#{batchSize, sequenceLength, headCount, vHeadSize}

import numpy as np
import sys
batchSize = 2
headCount = 8
seqlen = 256
vheadsize = 160

TensorSize = batchSize*seqlen*headCount*1*vheadsize
outTensor = np.arange(TensorSize).reshape(batchSize,headCount,seqlen, vheadsize)
print("outTensor.shape is",outTensor.shape)
outTensor.tofile('TensorBeforeTranspose',sep=" ",format="%s")
print("outTensorBeforeTranspose write complete")
outTensorTranspose = outTensor.transpose(0,2,1,3)
print("outTensorTranspose.shape is",outTensorTranspose.shape)
print("outTensorTranspose.strides is",outTensorTranspose.strides)
outTensorTranspose.tofile('TensorAfterTranspose',sep=" ",format="%s")
print("outTensorAfterTranspose write complete")


outTensor.shape is (2, 8, 256, 160)
outTensorBeforeTranspose write complete
outTensorTranspose.shape is (2, 256, 8, 160)
outTensorTranspose.strides is (1310720, 640, 163840, 4)
outTensorAfterTranspose write complete
